version: "3.8"

services:
  webserver:
    container_name: webserver
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
      args:
#        - BASE=nginx:1.25.4
        - UID=${UID:-1000}
        - GID=${GID:-1000}
#        - USER=${USER:-laravel}
    restart: unless-stopped
    ports:
      - "${WEBSERVER_EXT_PORT:-8086}:80"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network
    depends_on:
      - php-app

  php-app:
    container_name: php-app
    build:
      context: .
      dockerfile: ./.docker/php-fpm/Dockerfile
    volumes:
      - ./:/var/www/html
      - ./.docker/php-fpm/conf.d/php.ini:/usr/local/etc/php/conf.d/laravel.ini
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    environment:
      TZ: Europe/Moscow
    depends_on:
      - postgres
      - redis
    ports:
      - "9000:9000"
    networks:
      - app-network


  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: "${DB_DATABASE:-postgres}"
      POSTGRES_USER: "${DB_USERNAME:-postgres}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-postgres}"
    networks:
      - app-network
    ports:
      - "${POSTGRES_EXT_PORT:-5432}:5432"
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "${DB_DATABASE:-postgres}",
          "-U",
          "${DB_USERNAME:-postgres}"
        ]
      retries: 5
      timeout: 5s

  node:
    container_name: node
    image: node:alpine
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "${VITE_EXT_PORT:-5173}:5173"
    profiles: [ "node" ]
    networks:
      - app-network

  redis:
    container_name: redis
    image: "redis:alpine"
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s

networks:
  app-network:
    name: app-network
    driver: bridge